services:
    web:
        build: 
            context: .
            dockerfile: dev-Dockerfile
        ports:
            - '4444:4444'
        restart: unless-stopped
        networks:
            - vertical-shelter

networks:
    vertical-shelter:
        driver: bridge
